AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for CovidNotify Application
Globals:
  Function:
    Timeout: 30

Resources:
  GetFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: covid_notify/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Get:
          Type: Api
          Properties:
            Path: /
            Method: get
  PostFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: covid_notify/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Post:
          Type: Api
          Properties:
            Path: /
            Method: post

Outputs:
  CovidNotifyApi:
    Description: "API Gateway URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
