AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for CovidNotify Application
Globals:
  Function:
    Runtime: python3.8
    Timeout: 30
Parameters:
  ServiceName:
    Type: String
    Default: CovidNotify
  NotificationSound:
    Type: String
    Default: classical
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/SecretsViewOnly

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "Prod"
      Name:
        Fn::Sub: "${ServiceName}-ApiGateway"
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: "./api.json"
      MethodSettings:
      - LoggingLevel: ERROR
        ResourcePath: "/*"
        HttpMethod: "*"

  GetInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 
        Fn::Sub: "${ServiceName}-GetInfo"
      CodeUri: covid_notify/
      Handler: app.lambda_handler
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/"
            Method: get

  SpeakerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 
        Fn::Sub: "${ServiceName}-Speaker"
      CodeUri: covid_notify/
      Handler: speaker.lambda_handler
      Events:
        Post:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/speak"
            Method: post

  NotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 
        Fn::Sub: "${ServiceName}-Notifier"
      CodeUri: covid_notify/
      Handler: notify.lambda_handler
      Role:
        Fn::GetAtt: LambdaRole.Arn
      Environment:
        Variables:
          SecretName: "apps/covid-notify"
          UserKey: "PushoverUser"
          TokenKey: "PushoverToken"
          NotificationSound: !Ref NotificationSound
      Events:
        Post:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/notify"
            Method: post
        OnSchedule:
          Type: Schedule
          Properties:
            Name: "covid-notify-notifier"
            Description: "Sends a daily case count notification every day at 11 am"
            Enabled: true
            Schedule: cron(0 16 * * ? *) # UTC time -> 16:00 = 11:00 AM EST, 15:00 = 11:00 AM EDT

  SecretsManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "apps/covid-notify"
      Description: "Secret values for the Covid Notify application"
      SecretString: '{"PushoverUser": "", "PushoverToken": ""}'

Outputs:
  CovidNotifyApi:
    Description: "API Gateway URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
