AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for CovidNotify Application
Globals:
  Function:
    Timeout: 30

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/SecretsViewOnly

  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: covid_notify/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Get:
          Type: Api
          Properties:
            Path: /
            Method: get

  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: covid_notify/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Post:
          Type: Api
          Properties:
            Path: /
            Method: post

  NotifyFunctionApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CovidNotify-NotifyApi
      CodeUri: covid_notify/
      Handler: notify.lambda_handler
      Runtime: python3.8
      Role:
        Fn::GetAtt: LambdaRole.Arn
      Environment:
        Variables:
          SecretName: "test"
          UserKey: "PushoverUser"
          TokenKey: "PushoverCovidNotifyToken"
      Events:
        Post:
          Type: Api
          Properties:
            Path: /notify
            Method: get

  # NotifyFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: CovidNotify-NotifySchedule
  #     CodeUri: covid_notify/
  #     Handler: notify.lambda_handler
  #     Runtime: python3.8
  #     Environment:
  #       Variables:
  #         pushoverToken: ""
  #         pushoverUser: ""
  #     Events:
  #       OnSchedule:
  #         Type: Schedule
  #         Properties:
  #           Name: "schedule-covid-notify"
  #           Description: "Runs the notify endpoint of the CovidNotify application every day at 11 am"
  #           Enabled: true
  #           Schedule: cron(0 11 * * ? *)

Outputs:
  CovidNotifyApi:
    Description: "API Gateway URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
